(()=>{if(window.top!==window)return
let e=1,a=0,v,o={},ov=null,S='fastFS',V='video.html5-main-video,ytd-player video,video',H='.ytp-gradient-bottom,.ytp-chrome-bottom,.ytp-chrome-top,.ytp-play-button,.ytp-show-cards-title,.ytp-watermark,ytd-player .ytp-ce-element'
const hide=()=>document.querySelectorAll(H).forEach(x=>x.style.display='none'),show=()=>document.querySelectorAll(H).forEach(x=>x.style.display='')
const enter=()=>{if(a)return;v=document.querySelector(V);if(!v)return;ov=document.createElement('div');Object.assign(ov.style,{position:'fixed',top:0,left:0,width:'100vw',height:'100vh',background:'black',display:'flex',justifyContent:'center',alignItems:'center',overflow:'hidden',zIndex:'9999999999'});document.body.appendChild(ov);o={parent:v.parentNode,next:v.nextSibling,style:{width:v.style.width,height:v.style.height,objectFit:v.style.objectFit}};ov.appendChild(v);Object.assign(v.style,{width:'100%',height:'100%',objectFit:'contain'});hide();document.documentElement.style.overflow='hidden';a=1;console.log('[Lite4YouTube] FS → ON')}
const exit=()=>{if(!a)return;if(v&&o.parent){o.next?o.parent.insertBefore(v,o.next):o.parent.appendChild(v);Object.assign(v.style,o.style)}if(ov){ov.remove();ov=null}show();document.documentElement.style.overflow='';a=0;console.log('[Lite4YouTube] FS → OFF')}
const toggle=()=>{if(!e)return;a?exit():enter()}
const keyHandler=k=>{if(!e)return;let c=k.key.toLowerCase();if(c=='f'||k.code=='KeyF'){k.preventDefault();k.stopPropagation();k.stopImmediatePropagation();toggle()}else if((c=='escape'||c=='esc')&&a){k.preventDefault();k.stopPropagation();k.stopImmediatePropagation();exit()}}
document.addEventListener('keydown',keyHandler,{capture:1});document.addEventListener('keypress',keyHandler,{capture:1});document.addEventListener('pointerdown',k=>{if(!e)return;if(k.target.closest('.ytp-fullscreen-button')){k.preventDefault();k.stopPropagation();toggle()}},{capture:1});document.addEventListener('dblclick',k=>{if(!e)return;if(k.target.matches(V)){k.preventDefault();k.stopPropagation();toggle()}},{capture:1})
chrome.runtime.onMessage.addListener(m=>{if(m.type=='L4Y_FS_CHANGED'){e=!!m.value;if(!e&&a)exit();console.log('[Lite4YouTube] FS set →',e)}})
chrome.storage.local.get(S,d=>{e=d.fastFS!==!1;console.log('[Lite4YouTube] FS init →',e)})
let lastUrl=location.href;setInterval(()=>{if(location.href!==lastUrl){lastUrl=location.href;if(a)exit()}},1e3)
})()
